<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/3
 * Time: 2:53
 */

namespace backend\filters;

use yii;
use yii\base\ActionFilter;

class Accss extends ActionFilter
{
  public function beforeAction($action)
  {
      $ignoreurl=Yii::$app->params['ignoreurl'];
      if (Yii::$app->user->isGuest && !in_array($action->uniqueId,$ignoreurl)) {
          header('location:'.yii\helpers\Url::to(['user/login'],true));
       exit();
      }
      if (!Yii::$app->user->can($action->uniqueId)&& !in_array($action->uniqueId,$ignoreurl)) {
          header('location:'.yii\helpers\Url::to(['user/not'],true));
          exit();
      }

      return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }
}