<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/30
 * Time: 22:06
 */

namespace backend\models;


use yii\db\ActiveRecord;

class GoodsDetail extends ActiveRecord
{
    public function rules()
    {
        return[
            [['goods_id','detail','status'],'required'],

        ]; // TODO: Change the autogenerated stub
    }

}