<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/30
 * Time: 22:01
 */

namespace backend\models;


use yii;
use yii\db\ActiveRecord;

class Goods extends ActiveRecord
{
    public function rules()
    {
        return [
            [['is_hot', 'is_new', 'is_bast', 'goods_on'], 'safe'],
            [['name', 'price', 'sort_num', 'status', 'category_id', 'brand_id', 'keywords', 'goods_num'], 'required']
        ]; // TODO: Change the autogenerated stub
    }

    public function CreateGoods($date)
    {

        if (empty($date)) {
            throw  new yii\db\Exception("没有数据");
        }
        if (empty($date["Goods"]["goods_on"])) {
            $date["Goods"]["goods_on"] = Yii::$app->security->generateRandomString(32);

        }
        $this->create_time = time();
        if ($this->load($date) === false) {
            throw  new yii\db\Exception("数据绑定失败");
        }
        if ($this->save() === false) {
            throw  new yii\db\Exception("添加上商品失败");
        }
        if (!empty($date["GoodsImages"]["url"])) {
            $GoodsImages = new GoodsImages();
            $arr = [];
            foreach ($date["GoodsImages"]["url"] as $url) {
                $arr[] = ['goods_id' => $this->id,
                    'url' => $url,
                    'status' => $date["Goods"]["status"],
                    'sort_num' => $date["Goods"]["sort_num"],
                    'create_time' => time()
                ];
            }
            $res = Yii::$app->db->createCommand()->batchInsert('{{%goods_images}}',
                ['goods_id', 'url', 'status', 'sort_num', 'create_time'], $arr)->execute();
            if ($res === false) {
                throw  new yii\db\Exception("保存图片失败");

            }

        }
        if ($date["GoodsDetail"]["detail"]) {
            $GoodsDetail = new GoodsDetail();

            $GoodsDetail->goods_id = $this->id;
            $GoodsDetail->status = $date["Goods"]["status"];
            $GoodsDetail->create_time = time();
            $GoodsDetail->load($date);
            if ($GoodsDetail->save() == false) {
                throw  new yii\db\Exception("添加detail数据失败");
            }
        }
        return true;
    }

//BELONGS_TO
    public function getGoodsimages()
    {
        return $this->hasMany(GoodsImages::className(), ['goods_id' => 'id']);
    }

    public function getGoodsdetail()
    {
        return $this->hasOne(GoodsDetail::className(), ['goods_id' => 'id']);
    }


}