<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/29
 * Time: 22:13
 */

namespace backend\models;




use creocoder\nestedsets\NestedSetsBehavior;
use yii\db\ActiveRecord;

class GoodsCategory extends ActiveRecord
{

    public function behaviors() {
//        NestedSetsBehavior
        return [
            'tree' => [
                'class' => NestedSetsBehavior::className(),
                 'leftAttribute' => 'left_key',
                 'rightAttribute' => 'right_key',
                 'depthAttribute' => 'level',
            ],
        ];

    }
    public function rules()
    {
        return[
            [['name','keywords','sort_num','status','is_menu',],'required'],
            ['pid','number']
        ]; // TODO: Change the autogenerated stub
    }
    public static function find()
    {
        return new GoodsQuery(get_called_class());
    }
}