<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/30
 * Time: 22:04
 */

namespace backend\models;


use yii\db\ActiveRecord;

class GoodsImages extends ActiveRecord
{
    public function rules()
    {
        return[
            [['url','goods_id','sort_num','status'],'required'],

        ]; // TODO: Change the autogenerated stub
    }

}