<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/7
 * Time: 16:15
 */

namespace frontend\models;


use yii\db\ActiveRecord;

class SmsLog extends ActiveRecord
{
//   public function rules()
//   {
//       return [['mobile','service','content','ip','create_time','status'],'required']; // TODO: Change the autogenerated stub
//   }


}